services:
  backend:
    build:
      context: ./Back
      dockerfile: ./docker/Dockerfile
    container_name: maze_backend
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./Front
      dockerfile: ./docker/Dockerfile
    container_name: maze_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules 
    environment:
      
      - CHOKIDAR_USEPOLLING=true 

networks:
  default:
    name: maze_network
